const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const ROOT=__dirname, DATA=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data')), PHOTOS=path.join(DATA,'photos'), STATE_FILE=path.join(DATA,'state.json');
const HOST=process.env.HOST||'127.0.0.1', PORT=Number(process.env.PORT||4317);
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png'};
let state, workCenters=[], queue=Promise.resolve();
const sessions=new Map(), loginAttempts=new Map();
const RETURN_CONDITIONS=new Set(['Excellent (No Wear/Oiled)','Clean & Good (Standard Condition)','Minor Wear (Slight cosmetic scuff)','Recalibrate (Dropped or burred)','Missing/Under Investigation']);
const ISSUEABLE_CONDITIONS=new Set(['Excellent (No Wear/Oiled)','Clean & Good (Standard Condition)','Minor Wear (Slight cosmetic scuff)']);
const EQUIPMENT_CATEGORY_TYPES=Object.freeze({'Block Gauges':'Block Gauge','Special Size Pins':'Pin Gauge','Special Block Gauges':'Special Block Gauge','Digital Caliper':'Digital Caliper','Micrometer':'Micrometer','Vernier Caliper':'Vernier Caliper','Thread Gauges':'Thread Gauge','Core-Hole Gauges':'Thread Core Hole Gauge'});
const BORROWABLE_GROUPS=Object.freeze(['Special Size Pins','Thread Gauges','Core-Hole Gauges','Block Gauges','Special Block Gauges','Digital Caliper','Micrometer','Vernier Caliper']);
const LEGACY_CATEGORY_GROUPS=Object.freeze({'Pin Gauge':'Special Size Pins','Thread Gauge':'Thread Gauges','Thread Core Hole Gauge':'Core-Hole Gauges'});
const EQUIPMENT_STATUSES=new Set(['Active','Non Active','Blocked','Under Calibration']),CATEGORY_ID_PREFIXES=Object.freeze({'Digital Caliper':'DC-01-','Micrometer':'MM-01-','Special Block Gauges':'SBG-01-','Vernier Caliper':'VC-01-'});
const EQUIPMENT_DETAIL_LIMITS=Object.freeze({department:80,gaugeToolId:80,equipmentName:100,manufacturer:100,model:100,serialNumber:80,assetTag:80,year:20,certificateNo:100,specification:200,resolution:80,range:100,calibrationInterval:40,calibrationType:80,metrologySupplier:120,calibrationDueDate:10,calibrationCertificate:120,status:30,condition:80,remark:500});
function equipmentDetails(body){const details={};for(const [key,max] of Object.entries(EQUIPMENT_DETAIL_LIMITS)){const value=String(body[key]??'').trim();if(value.length>max)throw Object.assign(Error(`${key} is too long (maximum ${max} characters).`),{status:400});details[key]=value}details.status=details.status||'Active';if(!EQUIPMENT_STATUSES.has(details.status))throw Object.assign(Error('Choose a valid equipment status.'),{status:400});if(details.calibrationDueDate&&!/^\d{4}-\d{2}-\d{2}$/.test(details.calibrationDueDate))throw Object.assign(Error('Enter a valid calibration due date.'),{status:400});return details}
function nextGaugeToolId(inventory,categoryGroup){const prefix=CATEGORY_ID_PREFIXES[categoryGroup];if(!prefix)return '';const escaped=prefix.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),pattern=new RegExp(`^${escaped}(\\d+)$`),max=inventory.filter(t=>(t.categoryGroup||t.group)===categoryGroup).reduce((n,t)=>Math.max(n,Number((String(t.gaugeToolId||'').match(pattern)||[])[1]||0)),0);return `${prefix}${String(max+1).padStart(3,'0')}`}
function duplicateRegister(inventory,details,exceptId=''){const candidate=[details.gaugeToolId&&['gaugeToolId','id'],details.serialNumber&&['serialNumber','assetNumber','assetTag'],details.assetTag&&['assetTag','assetNumber','serialNumber']].filter(Boolean);return inventory.some(item=>item.id!==exceptId&&candidate.some(([key,...others])=>[key,...others].some(existing=>String(item[existing]||'').trim().toLowerCase()===String(details[key]||'').trim().toLowerCase())))}
const good=(v,n=200)=>typeof v==='string'&&v.trim().length>0&&v.trim().length<=n;
const active=l=>!l.returnedAt;
const publicUser=u=>({name:u.name,username:u.username,role:u.role,active:u.active!==false,mustChangePassword:!!u.mustChangePassword});
const publicAccount=u=>({name:u.name,username:u.username,role:u.role,active:u.active!==false,mustChangePassword:!!u.mustChangePassword,createdAt:u.createdAt||null,passwordChangedAt:u.passwordChangedAt||null});
const accountList=()=>state.users.map(publicAccount);
const activeAdmins=()=>state.users.filter(u=>u.role==='superuser'&&u.active!==false).length;
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function verifyPassword(password,user){const actual=crypto.scryptSync(password,user.salt,64),stored=Buffer.from(user.hash,'hex');return stored.length===actual.length&&crypto.timingSafeEqual(actual,stored)}
function adminOnly(user){return user?.role==='superuser'}
const sessionCookiePolicy=()=>process.env.NODE_ENV==='production'?'; SameSite=None; Secure':'; SameSite=Strict';
function parseCookie(req){const raw=req.headers.cookie||'';const m=raw.match(/(?:^|;\s*)gauge_session=([a-f0-9]{64})(?:;|$)/);return m?.[1]||''}
function actor(req){const sid=parseCookie(req),u=sessions.get(sid);return u||null}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data))}
async function readJson(req,limit=8*1024*1024){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>limit)throw Object.assign(Error('Request is too large.'),{status:413});chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(Error('Request must contain valid JSON.'),{status:400})}}
async function save(){const tmp=STATE_FILE+'.tmp';await fs.writeFile(tmp,JSON.stringify(state,null,2));await fs.rename(tmp,STATE_FILE)}
function write(fn){const p=queue.then(async()=>{await fn();await save()});queue=p.catch(()=>{});return p}
function record(req,values){return {at:new Date().toISOString(),recordedBy:req.user.name,recordedByUsername:req.user.username,...values}}
async function init(){await fs.mkdir(PHOTOS,{recursive:true});workCenters=JSON.parse(await fs.readFile(path.join(ROOT,'work-centers.json'),'utf8'));try{state=JSON.parse(await fs.readFile(STATE_FILE,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;state={staff:[],loans:[],audit:[],calibrations:{},users:[]}}
state.staff||=[];state.loans||=[];state.audit||=[];state.calibrations||={};state.equipment||=[];state.registerDetails||={};state.borrowGroups=Object.fromEntries(BORROWABLE_GROUPS.map(group=>[group,state.borrowGroups?.[group]!==false]));state.users||=[];let migrated=false;state.users.forEach(u=>{if(u.active===undefined){u.active=true;migrated=true}});
if(!state.users.some(u=>u.username.toLowerCase()==='admin')){const initialPassword=process.env.ADMIN_INITIAL_PASSWORD||(process.env.NODE_ENV==='production'?null:'superadmin123');if(!initialPassword)throw Error('Set ADMIN_INITIAL_PASSWORD before starting a new production data store.');if(initialPassword.length<12)throw Error('ADMIN_INITIAL_PASSWORD must contain at least 12 characters.');const h=hashPassword(initialPassword);state.users.push({name:'Admin',username:'Admin',role:'superuser',active:true,salt:h.salt,hash:h.hash,mustChangePassword:true,createdAt:new Date().toISOString()});migrated=true}if(migrated)await save()}
function requireUser(req,res,allowPasswordSetup=false){const signed=actor(req),stored=signed&&state.users.find(u=>u.username===signed.username);req.user=stored?publicUser(stored):null;if(!req.user||!req.user.active){send(res,401,{error:'Sign in is required.'});return false}if(req.user.mustChangePassword&&!allowPasswordSetup){send(res,403,{error:'Change the initial password before using the tracker.'});return false}return true}
function requireAdmin(req,res){if(!requireUser(req,res))return false;if(!adminOnly(req.user)){send(res,403,{error:'Only the Admin superuser can manage staff accounts.'});return false}return true}
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/session'){const u=actor(req);return send(res,200,{user:u||null})}
 if(req.method==='POST'&&url.pathname==='/api/login'){
  const ip=req.socket.remoteAddress||'unknown',now=Date.now(),a=loginAttempts.get(ip)||{count:0,until:0};if(a.until>now)return send(res,429,{error:'Too many sign-in attempts. Wait 15 minutes and try again.'});
  const b=await readJson(req);const user=state.users.find(u=>u.username.toLowerCase()===String(b.username||'').trim().toLowerCase());
  if(!user||user.active===false||typeof b.password!=='string'||!verifyPassword(b.password,user)){a.count++;if(a.count>=8){a.count=0;a.until=now+15*60*1000}loginAttempts.set(ip,a);return send(res,401,{error:'Username or password is incorrect.'})}
  loginAttempts.delete(ip);const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,publicUser(user));const cookiePolicy=sessionCookiePolicy();
  return send(res,200,{user:publicUser(user)},{'Set-Cookie':`gauge_session=${sid}; HttpOnly${cookiePolicy}; Path=/; Max-Age=43200`});
 }
 if(req.method==='POST'&&url.pathname==='/api/logout'){const sid=parseCookie(req);if(sid)sessions.delete(sid);return send(res,200,{ok:true},{'Set-Cookie':`gauge_session=; HttpOnly${sessionCookiePolicy()}; Path=/; Max-Age=0`})}
 if(req.method==='POST'&&url.pathname==='/api/password'){
  if(!requireUser(req,res,true))return;const b=await readJson(req);if(!good(b.newPassword,200)||b.newPassword.length<12)return send(res,400,{error:'New password must contain at least 12 characters.'});const user=state.users.find(u=>u.username===req.user.username);if(!user||!verifyPassword(String(b.currentPassword||''),user))return send(res,401,{error:'Current password is incorrect.'});
  const h=hashPassword(b.newPassword);await write(async()=>{user.salt=h.salt;user.hash=h.hash;user.mustChangePassword=false;user.passwordChangedAt=new Date().toISOString();state.audit.push(record(req,{event:'Password changed',staff:user.name,details:'Account password updated.'}))});sessions.set(parseCookie(req),publicUser(user));return send(res,200,{user:publicUser(user)});
 }
 if(!requireUser(req,res))return;
 const sourceInventory=JSON.parse(await fs.readFile(path.join(ROOT,'inventory.json'),'utf8'));const inventory=[...sourceInventory.map(t=>{const detail=state.registerDetails[t.id]||{},categoryGroup=detail.categoryGroup||LEGACY_CATEGORY_GROUPS[t.type]||null,defaultName=t.type==='Pin Gauge'?`Pin Gauge Ø${t.size}${t.unit?' '+t.unit:''}`:`${t.type} ${t.size||''}`.trim();return {...t,...detail,status:detail.status||t.status||'Active',equipmentName:detail.equipmentName||defaultName,gaugeToolId:detail.gaugeToolId||t.id,categoryGroup,registered:false,masterRegistered:true}}),...state.equipment.map(t=>({...t,status:t.status||'Active',masterRegistered:true}))];
 const safeInventory=adminOnly(req.user)?inventory:inventory.map(t=>t.registered||t.masterRegistered?(({id,type,categoryGroup,group,size,unit,qty,registered,masterRegistered,gaugeToolId,equipmentName,status})=>({id,type,categoryGroup,group,size,unit,qty,registered,masterRegistered,gaugeToolId,equipmentName,status}))(t):t);
 if(req.method==='POST'&&url.pathname==='/api/settings/save-all'){if(!requireAdmin(req,res))return;try{await write(async()=>{state.audit.push(record(req,{event:'Settings saved',details:'Administrator saved all tracker settings and current records.'}))});return send(res,200,{ok:true,savedAt:new Date().toISOString(),message:'All settings and tracker records are saved.'})}catch(e){return send(res,e.status||500,{error:e.message||'Could not save tracker settings.'})}}
 if(req.method==='POST'&&url.pathname==='/api/settings/borrow-groups'){if(!requireAdmin(req,res))return;const b=await readJson(req),groups=b.groups;if(!groups||typeof groups!=='object'||Array.isArray(groups)||!BORROWABLE_GROUPS.every(group=>typeof groups[group]==='boolean'))return send(res,400,{error:'Select Show or Hide for every equipment group.'});try{await write(async()=>{state.borrowGroups=Object.fromEntries(BORROWABLE_GROUPS.map(group=>[group,groups[group]]));const shown=BORROWABLE_GROUPS.filter(group=>state.borrowGroups[group]);state.audit.push(record(req,{event:'Borrower group visibility updated',details:`Borrower selection enabled for: ${shown.join(', ')||'no equipment groups'}.`}))});return send(res,200,{borrowGroups:state.borrowGroups})}catch(e){return send(res,e.status||500,{error:e.message||'Could not save borrower group visibility.'})}}
 if(req.method==='GET'&&url.pathname==='/api/bootstrap')return send(res,200,{inventory:safeInventory,workCenters,...state,equipment:undefined,registerDetails:undefined,users:undefined,accounts:adminOnly(req.user)?accountList():[]});
 if(req.method==='GET'&&url.pathname==='/api/inventory/borrow-view'){const item=inventory.find(t=>t.id===url.searchParams.get('id'));if(!item)return send(res,404,{error:'Equipment was not found.'});const borrowGroup=item.categoryGroup||LEGACY_CATEGORY_GROUPS[item.type]||item.group;if(!adminOnly(req.user)&&borrowGroup&&state.borrowGroups[borrowGroup]===false)return send(res,403,{error:'This equipment group is not enabled for borrower access.'});const {id,type,categoryGroup,group,size,unit,registered,gaugeToolId,department,equipmentName,manufacturer,model,serialNumber,assetTag,year,specification,resolution,range,calibrationInterval,calibrationType,metrologySupplier,calibrationDueDate,calibrationCertificate,certificateNo,condition,status}=item;return send(res,200,{item:{id,type,categoryGroup,group,size,unit,registered,gaugeToolId,department,equipmentName,manufacturer,model,serialNumber,assetTag,year,specification,resolution,range,calibrationInterval,calibrationType,metrologySupplier,calibrationDueDate,calibrationCertificate,certificateNo,condition,status}})}
 if(req.method==='POST'&&url.pathname==='/api/inventory/register'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),categoryGroup=String(b.categoryGroup||'').trim(),unit=String(b.unit||'').trim();if(!Object.hasOwn(EQUIPMENT_CATEGORY_TYPES,categoryGroup))return send(res,400,{error:'Choose a category group from the metrology list.'});if(unit.length>20)return send(res,400,{error:'Unit is too long.'});let details;try{details=equipmentDetails(b)}catch(e){return send(res,e.status||400,{error:e.message})}if(!good(details.equipmentName,100))return send(res,400,{error:'Equipment Name is required.'});if(details.condition&&!RETURN_CONDITIONS.has(details.condition))return send(res,400,{error:'Choose a valid equipment condition.'});const trackerId=`EG-${crypto.randomUUID().toUpperCase()}`,item={id:trackerId,...details,type:EQUIPMENT_CATEGORY_TYPES[categoryGroup],categoryGroup,group:categoryGroup,size:details.equipmentName,unit,qty:1,assetNumber:details.assetTag||details.serialNumber,registered:true,registeredAt:new Date().toISOString(),registeredBy:req.user.name,gaugeToolId:details.gaugeToolId||trackerId};if(duplicateRegister(inventory,details))return send(res,409,{error:'That Gauge / tool ID, serial number, or asset tag is already registered.'});
  await write(async()=>{if(CATEGORY_ID_PREFIXES[categoryGroup]){item.gaugeToolId=nextGaugeToolId([...inventory,...state.equipment],categoryGroup);details.gaugeToolId=item.gaugeToolId}if(duplicateRegister([...inventory,...state.equipment],details))throw Object.assign(Error('That Gauge / tool ID, serial number, or asset tag is already registered.'),{status:409});state.equipment.push(item);if(details.certificateNo||details.calibrationCertificate){const certificate=details.certificateNo||details.calibrationCertificate,dueDate=details.calibrationDueDate||'';if(dueDate)state.calibrations[item.id]={certificate,dueDate,recordedBy:req.user.name,recordedAt:new Date().toISOString()}}state.audit.push(record(req,{event:'Equipment registered',toolId:item.id,details:`${categoryGroup} · ${details.equipmentName}${item.assetNumber?' · '+item.assetNumber:''}`}))});return send(res,201,{item,state:{...state,users:undefined,equipment:undefined,registerDetails:undefined}})
 }
 if(req.method==='POST'&&url.pathname==='/api/inventory/update'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),item=inventory.find(t=>t.id===String(b.id||''));if(!item||!item.masterRegistered)return send(res,404,{error:'Registered equipment was not found.'});const categoryGroup=String(b.categoryGroup||'').trim(),unit=String(b.unit||'').trim();if(!Object.hasOwn(EQUIPMENT_CATEGORY_TYPES,categoryGroup))return send(res,400,{error:'Choose a category group from the register list.'});if(unit.length>20)return send(res,400,{error:'Unit is too long.'});let details;try{details=equipmentDetails(b)}catch(e){return send(res,e.status||400,{error:e.message})}if(!good(details.equipmentName,100))return send(res,400,{error:'Equipment Name is required.'});if(details.condition&&!RETURN_CONDITIONS.has(details.condition))return send(res,400,{error:'Choose a valid equipment condition.'});if(duplicateRegister(inventory,details,item.id))return send(res,409,{error:'That Gauge / tool ID, serial number, or asset tag is already registered.'});const registeredItem=state.equipment.find(t=>t.id===item.id);await write(async()=>{const update={...details,categoryGroup,unit,updatedAt:new Date().toISOString(),updatedBy:req.user.name};if(registeredItem){Object.assign(registeredItem,update,{group:categoryGroup,type:EQUIPMENT_CATEGORY_TYPES[categoryGroup],size:details.equipmentName,assetNumber:details.assetTag||details.serialNumber,gaugeToolId:details.gaugeToolId||registeredItem.id})}else state.registerDetails[item.id]={...(state.registerDetails[item.id]||{}),...update,gaugeToolId:details.gaugeToolId||item.id};Object.assign(item,update);if(registeredItem){Object.assign(item,{group:categoryGroup,type:EQUIPMENT_CATEGORY_TYPES[categoryGroup],size:details.equipmentName,assetNumber:details.assetTag||details.serialNumber,gaugeToolId:details.gaugeToolId||registeredItem.id})}else Object.assign(item,{gaugeToolId:details.gaugeToolId||item.id});if(details.certificateNo||details.calibrationCertificate){const certificate=details.certificateNo||details.calibrationCertificate;if(details.calibrationDueDate){state.calibrations[item.id]={certificate,dueDate:details.calibrationDueDate,recordedBy:req.user.name,recordedAt:new Date().toISOString()};item.certificateNo=certificate;item.calibrationDueDate=details.calibrationDueDate}else delete state.calibrations[item.id]}else delete state.calibrations[item.id];state.audit.push(record(req,{event:'Equipment register updated',toolId:item.id,details:`${categoryGroup} · ${details.equipmentName}`}))});return send(res,200,{item,state:{...state,users:undefined,equipment:undefined,registerDetails:undefined}})
 } if(req.method==='GET'&&url.pathname==='/api/export'){if(!requireAdmin(req,res))return;return send(res,200,{exportedAt:new Date().toISOString(),inventorySource:'Equipment & Gauge BorrowReturn Tracker.xlsx',workCenters,...state,photoStorage:'Copy data/photos separately to preserve image evidence.',users:state.users.map(u=>({name:u.name,username:u.username,role:u.role,createdAt:u.createdAt,passwordChangedAt:u.passwordChangedAt}))})}
 if(req.method==='GET'&&url.pathname.startsWith('/api/photos/')){const file=path.basename(url.pathname.slice(12));if(!/^[a-f0-9-]{36}\.(jpg|png|webp)$/.test(file))return send(res,400,{error:'Invalid photo identifier.'});try{const bytes=await fs.readFile(path.join(PHOTOS,file));res.writeHead(200,{'Content-Type':file.endsWith('.png')?'image/png':file.endsWith('.webp')?'image/webp':'image/jpeg','Cache-Control':'private, max-age=3600','X-Content-Type-Options':'nosniff'});return res.end(bytes)}catch{return send(res,404,{error:'Photo was not found.'})}}
 if(req.method==='POST'&&url.pathname==='/api/photos'){const b=await readJson(req);if(typeof b.dataUrl!=='string')return send(res,400,{error:'Photo is missing.'});const m=b.dataUrl.match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!m)return send(res,400,{error:'Photo must be JPEG, PNG, or WebP.'});const bytes=Buffer.from(m[2],'base64');if(bytes.length>5*1024*1024)return send(res,413,{error:'Compressed photo must be under 5 MB.'});const ext=m[1]==='jpeg'?'jpg':m[1],photoId=`${crypto.randomUUID()}.${ext}`;await fs.writeFile(path.join(PHOTOS,photoId),bytes,{flag:'wx'});return send(res,201,{photoId})}
 if(req.method==='POST'&&url.pathname==='/api/users'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),name=String(b.name||'').trim(),username=String(b.username||'').trim(),role=b.role;if(!good(name,80)||!good(username,50)||!/^[A-Za-z0-9._-]+$/.test(username))return send(res,400,{error:'Enter a name and a username using letters, numbers, dot, dash, or underscore.'});if(!['staff','superuser'].includes(role))return send(res,400,{error:'Choose Staff or Administrator.'});if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)return send(res,400,{error:'Passwords must contain at least 12 characters.'});
  try{await write(async()=>{if(state.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw Object.assign(Error('That username is already registered.'),{status:409});if(state.users.some(u=>u.name.toLowerCase()===name.toLowerCase()))throw Object.assign(Error('That name already has an account.'),{status:409});const h=hashPassword(b.password),user={name,username,role,active:true,mustChangePassword:true,salt:h.salt,hash:h.hash,createdAt:new Date().toISOString()};state.users.push(user);if(role==='staff'&&!state.staff.includes(name))state.staff.push(name);if(role==='superuser')state.staff=state.staff.filter(n=>n!==name);state.audit.push(record(req,{event:'User account created',staff:name,details:`${role==='superuser'?'Administrator':'Staff'} account · username ${username}`}))});return send(res,201,{accounts:accountList(),staff:state.staff})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/users/update'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),target=state.users.find(u=>u.username===String(b.username||'')),name=String(b.name||'').trim(),username=String(b.newUsername||'').trim(),role=b.role;if(!target)return send(res,404,{error:'User account was not found.'});if(target.username===req.user.username)return send(res,403,{error:'Use Account & data to change your own password. Another Administrator must edit your account.'});if(!good(name,80)||!good(username,50)||!/^[A-Za-z0-9._-]+$/.test(username))return send(res,400,{error:'Enter a name and a username using letters, numbers, dot, dash, or underscore.'});if(!['staff','superuser'].includes(role))return send(res,400,{error:'Choose Staff or Administrator.'});if(b.password!==''&&b.password!==undefined&&(typeof b.password!=='string'||b.password.length<12||b.password.length>200))return send(res,400,{error:'Passwords must contain at least 12 characters.'});
  try{await write(async()=>{if(state.users.some(u=>u!==target&&u.username.toLowerCase()===username.toLowerCase()))throw Object.assign(Error('That username is already registered.'),{status:409});if(state.users.some(u=>u!==target&&u.name.toLowerCase()===name.toLowerCase()))throw Object.assign(Error('That name already has an account.'),{status:409});if(name!==target.name&&state.loans.some(l=>active(l)&&l.staff===target.name))throw Object.assign(Error('Record active loans before changing this staff name.'),{status:409});if(target.role==='superuser'&&target.active!==false&&role!=='superuser'&&activeAdmins()<=1)throw Object.assign(Error('At least one active Administrator account must remain.'),{status:409});const oldName=target.name,oldUsername=target.username,oldRole=target.role;state.staff=state.staff.filter(n=>n!==oldName);target.name=name;target.username=username;target.role=role;if(role==='staff'&&target.active!==false&&!state.staff.includes(name))state.staff.push(name);if(b.password){const h=hashPassword(b.password);target.salt=h.salt;target.hash=h.hash;target.mustChangePassword=true;target.passwordChangedAt=null}for(const [sid,su] of sessions)if(su.username===oldUsername)sessions.delete(sid);state.audit.push(record(req,{event:'User account updated',staff:name,details:`${oldRole} → ${role} · username ${username}${b.password?' · password reset; change required at next sign-in':''}`}))});return send(res,200,{accounts:accountList(),staff:state.staff})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/users/toggle'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),target=state.users.find(u=>u.username===String(b.username||''));if(!target)return send(res,404,{error:'User account was not found.'});if(target.username===req.user.username)return send(res,403,{error:'You cannot disable your own account.'});if(typeof b.active!=='boolean')return send(res,400,{error:'Choose an account status.'});if(target.active===b.active)return send(res,400,{error:'The account already has that status.'});if(!b.active&&target.role==='superuser'&&activeAdmins()<=1)return send(res,409,{error:'At least one active Administrator account must remain.'});
  await write(async()=>{target.active=b.active;if(target.role==='staff'){if(b.active){if(!state.staff.includes(target.name))state.staff.push(target.name)}else state.staff=state.staff.filter(n=>n!==target.name)}if(!b.active)for(const [sid,su] of sessions)if(su.username===target.username)sessions.delete(sid);state.audit.push(record(req,{event:`User account ${b.active?'enabled':'disabled'}`,staff:target.name,details:`${target.role==='superuser'?'Administrator':'Staff'} account access ${b.active?'enabled':'disabled'}.`}))});return send(res,200,{accounts:accountList(),staff:state.staff})
 }
 if(req.method==='POST'&&url.pathname==='/api/users/delete'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),target=state.users.find(u=>u.username===String(b.username||''));if(!target)return send(res,404,{error:'User account was not found.'});if(target.username===req.user.username)return send(res,403,{error:'You cannot delete your own account.'});if(target.role==='superuser'&&target.active!==false&&activeAdmins()<=1)return send(res,409,{error:'At least one active Administrator account must remain.'});if(state.loans.some(l=>active(l)&&l.staff===target.name))return send(res,409,{error:'Record this staff member’s active loans before deleting the account.'});
  await write(async()=>{state.users=state.users.filter(u=>u!==target);state.staff=state.staff.filter(n=>n!==target.name);for(const [sid,su] of sessions)if(su.username===target.username)sessions.delete(sid);state.audit.push(record(req,{event:'User account deleted',staff:target.name,details:`${target.role==='superuser'?'Administrator':'Staff'} account deleted; historical records retained.`}))});return send(res,200,{accounts:accountList(),staff:state.staff})
 }
 if(req.method==='POST'&&url.pathname==='/api/staff'){
  if(!requireAdmin(req,res))return;const b=await readJson(req);const name=String(b.name||'').trim(),username=String(b.username||'').trim();if(!good(name,80)||!good(username,50)||!/^[A-Za-z0-9._-]+$/.test(username))return send(res,400,{error:'Enter a staff name and a username using letters, numbers, dot, dash, or underscore.'});if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)return send(res,400,{error:'Staff passwords must contain at least 12 characters.'});
  try{await write(async()=>{if(state.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw Object.assign(Error('That username is already registered.'),{status:409});if(state.users.some(u=>u.name.toLowerCase()===name.toLowerCase()))throw Object.assign(Error('That staff name already has an account.'),{status:409});const h=hashPassword(b.password);state.users.push({name,username,role:'staff',salt:h.salt,hash:h.hash,createdAt:new Date().toISOString()});if(!state.staff.includes(name))state.staff.push(name);state.audit.push(record(req,{event:'Staff account registered',staff:name,details:`Username ${username}`}))});return send(res,201,{state:{...state,users:undefined,registerDetails:undefined}})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/staff/remove'){
  if(!requireAdmin(req,res))return;const b=await readJson(req);try{await write(async()=>{const name=String(b.name||'').trim();if(name==='Admin')throw Object.assign(Error('The Admin superuser account cannot be removed.'),{status:403});if(state.loans.some(l=>active(l)&&l.staff===name))throw Object.assign(Error('This staff member has an active loan. Record its return first.'),{status:409});const i=state.users.findIndex(u=>u.name===name&&u.role!=='superuser');if(i<0)throw Object.assign(Error('Staff account was not found.'),{status:404});const [u]=state.users.splice(i,1);state.staff=state.staff.filter(x=>x!==name);for(const [sid,su] of sessions)if(su.username===u.username)sessions.delete(sid);state.audit.push(record(req,{event:'Staff account removed',staff:name,details:'Account removed; historical records retained.'}))});return send(res,200,{state:{...state,users:undefined,registerDetails:undefined}})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/calibration'){
  const b=await readJson(req),t=inventory.find(x=>x.id===b.toolId);if(!t)return send(res,404,{error:'Gauge was not found.'});if(t.masterRegistered&&!adminOnly(req.user))return send(res,403,{error:'Only an Administrator can edit register and calibration details.'});const certificate=String(b.certificate||'').trim()||`CAL-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${t.id}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;if(!good(certificate,100)||!/^\d{4}-\d{2}-\d{2}$/.test(b.dueDate||''))return send(res,400,{error:'Certificate reference and due date are required.'});
  await write(async()=>{state.calibrations[t.id]={certificate,dueDate:b.dueDate,updatedAt:new Date().toISOString(),updatedBy:req.user.name};if(t.masterRegistered){if(t.registered){t.certificateNo=certificate;t.calibrationDueDate=b.dueDate}else state.registerDetails[t.id]={...(state.registerDetails[t.id]||{}),certificateNo:certificate,calibrationDueDate:b.dueDate}}state.audit.push(record(req,{event:'Calibration updated',toolId:t.id,details:`Cert ${certificate} · due ${b.dueDate}`}))});return send(res,200,{state:{...state,users:undefined,registerDetails:undefined}})
 }
 if(req.method==='POST'&&url.pathname==='/api/calibration/bulk'){
  if(!requireAdmin(req,res))return;const b=await readJson(req),dueDate='2027-12-30';if(b.confirmed!==true||b.dueDate!==dueDate)return send(res,400,{error:'Confirm the approved 30/12/2027 calibration due date for all inventory items.'});let generated=0;
  await write(async()=>{const updatedAt=new Date().toISOString();for(const t of inventory){const current=state.calibrations[t.id]||{},oldCertificate=String(current.certificate||'').trim(),certificate=oldCertificate||`CAL-BULK-${dueDate.replaceAll('-','')}-${t.id}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;if(!oldCertificate)generated++;state.calibrations[t.id]={...current,certificate,dueDate,updatedAt,updatedBy:req.user.name};if(t.masterRegistered){if(t.registered){t.certificateNo=certificate;t.calibrationDueDate=dueDate}else state.registerDetails[t.id]={...(state.registerDetails[t.id]||{}),certificateNo:certificate,calibrationDueDate:dueDate}}}state.audit.push(record(req,{event:'Bulk calibration setup',details:`${inventory.length} equipment and gauges set to due ${dueDate}; ${generated} internal tracking references generated. Existing certificate references preserved.`}))});return send(res,200,{state:{...state,users:undefined,registerDetails:undefined},updatedCount:inventory.length,generatedCount:generated,dueDate})
 }
 if(req.method==='POST'&&url.pathname==='/api/borrow'){
  const b=await readJson(req),t=inventory.find(x=>x.id===b.toolId),machine=workCenters.find(x=>x.machine===b.machine);if(!t)return send(res,404,{error:'Gauge was not found.'});const borrowGroup=t.categoryGroup||LEGACY_CATEGORY_GROUPS[t.type]||t.group;if(borrowGroup&&state.borrowGroups[borrowGroup]===false)return send(res,403,{error:'This equipment group is not enabled for borrower access.'});if(!state.staff.includes(b.staff))return send(res,400,{error:'Choose staff from the registered staff list.'});if(!good(b.jobOrder?.trim(),80)||!good(b.drawing?.trim(),80)||!good(b.photoId,60))return send(res,400,{error:'Staff, job order, drawing, and borrow photo are required.'});if(!machine||machine.workCenter!==b.workCenter)return send(res,400,{error:'Select a machine and its matching work center from the list.'});if(t.status&&t.status!=='Active')return send(res,409,{error:`${t.gaugeToolId||t.id} is marked ${t.status} and cannot be borrowed.`});if(!ISSUEABLE_CONDITIONS.has(b.condition))return send(res,400,{error:'Select a serviceable issue condition. Recalibration or investigation items cannot be issued.'});const start=new Date(b.borrowedAt),due=new Date(b.dueAt);if(isNaN(+start)||isNaN(+due)||due<=start)return send(res,400,{error:'Expected return must be after borrow time.'});const c=state.calibrations[t.id];if(!c?.certificate||!c.dueDate||c.dueDate<start.toISOString().slice(0,10))return send(res,400,{error:'This gauge has no current calibration record.'});try{await fs.access(path.join(PHOTOS,path.basename(b.photoId)))}catch{return send(res,400,{error:'Borrow photo is missing on the server.'})}
  try{await write(async()=>{if(state.loans.some(l=>active(l)&&l.toolId===t.id))throw Object.assign(Error('This gauge already has an active loan.'),{status:409});const loanId=`GL-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,loan={loanId,toolId:t.id,toolType:t.type,toolGroup:t.group,gaugeSize:t.size,unit:t.unit,staff:b.staff,jobOrder:b.jobOrder.trim(),drawing:b.drawing.trim(),machine:machine.machine,workCenter:machine.workCenter,borrowedAt:start.toISOString(),dueAt:due.toISOString(),calibrationCertificate:c.certificate,calibrationDue:c.dueDate,borrowPhotoId:path.basename(b.photoId),recordedBy:req.user.name,issueCondition:b.condition,notes:b.notes||'',returnedAt:null};state.loans.push(loan);state.audit.push(record(req,{event:'Borrow',loanId,staff:loan.staff,toolId:t.id,jobOrder:loan.jobOrder,drawing:loan.drawing,machine:loan.machine,workCenter:loan.workCenter,photoId:loan.borrowPhotoId,details:`${t.group} · ${t.size}${t.unit?' '+t.unit:''} · ${machine.machine} · ${machine.workCenter} · due ${due.toISOString()}`}))});return send(res,201,{state:{...state,users:undefined,registerDetails:undefined}})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/return'){
  const b=await readJson(req),when=new Date(b.returnedAt);if(!good(b.photoId,60)||b.conditionOK!==true||!RETURN_CONDITIONS.has(b.physicalCondition)||isNaN(+when))return send(res,400,{error:'Return photo, physical condition assessment, visual check, and return time are required.'});try{await fs.access(path.join(PHOTOS,path.basename(b.photoId)))}catch{return send(res,400,{error:'Return photo is missing on the server.'})}
  try{await write(async()=>{const l=state.loans.find(x=>x.loanId===b.loanId);if(!l)throw Object.assign(Error('Loan was not found.'),{status:404});if(!active(l))throw Object.assign(Error('This loan is already returned.'),{status:409});if(when<new Date(l.borrowedAt))throw Object.assign(Error('Return cannot predate borrow.'),{status:400});l.returnedAt=when.toISOString();l.returnRecordedBy=req.user.name;l.returnPhotoId=path.basename(b.photoId);l.returnConditionOK=true;l.returnPhysicalCondition=b.physicalCondition;l.returnNotes=b.notes||'';state.audit.push(record(req,{event:'Return',loanId:l.loanId,staff:l.staff,toolId:l.toolId,jobOrder:l.jobOrder,drawing:l.drawing,machine:l.machine,workCenter:l.workCenter,photoId:l.returnPhotoId,details:`Returned · physical condition: ${l.returnPhysicalCondition} · visual check complete${l.returnNotes?' · '+l.returnNotes:''}`}))});return send(res,200,{state:{...state,users:undefined,registerDetails:undefined}})}catch(e){return send(res,e.status||400,{error:e.message})}
 }
 if(req.method==='POST'&&url.pathname==='/api/loans/delete'){if(!requireAdmin(req,res))return;const b=await readJson(req),loanId=String(b.loanId||'').trim();if(!good(loanId,80))return send(res,400,{error:'Select a valid loan record to delete.'});try{await write(async()=>{const index=state.loans.findIndex(l=>l.loanId===loanId);if(index<0)throw Object.assign(Error('Loan record was not found.'),{status:404});const [loan]=state.loans.splice(index,1),recordStatus=active(loan)?'Open':'Returned';state.audit.push(record(req,{event:'Loan record deleted',loanId:loan.loanId,staff:loan.staff,toolId:loan.toolId,jobOrder:loan.jobOrder,drawing:loan.drawing,machine:loan.machine,workCenter:loan.workCenter,photoId:loan.returnPhotoId||loan.borrowPhotoId,details:`${recordStatus} loan deleted by administrator · expected return ${loan.dueAt||'not set'}${loan.returnedAt?` · returned ${loan.returnedAt}`:''} · photos retained (borrow: ${loan.borrowPhotoId||'none'}; return: ${loan.returnPhotoId||'none'}).`}))});return send(res,200,{state:{...state,users:undefined,registerDetails:undefined}})}catch(e){return send(res,e.status||500,{error:e.message||'Could not delete loan record.'})}} return send(res,404,{error:'API route not found.'})
}
async function serve(req,res){const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(req.method==='GET'&&url.pathname==='/healthz')return send(res,200,{ok:true});if(url.pathname.startsWith('/api/'))return await api(req,res,url);let route=decodeURIComponent(url.pathname);if(route==='/')route='/index.html';const file=path.resolve(ROOT,'.'+route),isLogo=route==='/assets/metrology-caliper-logo.png',allowed=['index.html','app.js','styles.css','inventory.json'];if(!isLogo&&(path.dirname(file)!==ROOT||!allowed.includes(path.basename(file))))return send(res,403,{error:'Forbidden.'});if(isLogo&&path.dirname(file)!==path.join(ROOT,'assets'))return send(res,403,{error:'Forbidden.'});const stat=await fs.stat(file);if(!stat.isFile())return send(res,404,{error:'Not found.'});res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});res.end(await fs.readFile(file))}catch(e){console.error(e);if(!res.headersSent)send(res,e.status||500,{error:e.message||'Server error.'});else res.destroy()}}
init().then(()=>http.createServer(serve).listen(PORT,HOST,()=>console.log(`Equipment & Gauge Borrow/Return Tracker available at http://${HOST}:${PORT}`))).catch(e=>{console.error('Could not start Equipment & Gauge Borrow/Return Tracker:',e);process.exit(1)});
